baseURL = 'https://monsdar.github.io/Basketball_Abzeichen/'
languageCode = 'de-de'
title = 'Basketball Abzeichen'
theme = 'basketball-theme'

[params]
  description = "Abzeichen-System f√ºr Mini Basketballtraining"
  author = "Nils Brinkmann"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]